[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[dependencies]
aocf = "0.1.15"
itertools = "0.10.1"
clap = "3.0.0-beta.5"
anyhow = "1.0.51"
termion = "1.5.6"
log = "0.4.14"
stderrlog = "0.5.1"
